obj-$(CONFIG_SENSORS)		+= sensors_class.o
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
obj-$(CONFIG_SENSORS_CM3623)	+= proxm_class/
obj-$(CONFIG_SENSORS_CM3623)	+= cm3623/
obj-$(CONFIG_SENSORS_CM3623)	+= al3010/
